name: ftmo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.3.0
  flutter_svg: ^2.0.10+1
  blur: ^4.0.0
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.13


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
 